services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - n8n
      - adminer
    restart: unless-stopped

  n8n:
    extends:
      file: compose.common.yaml
      service: n8n
    environment:
      - NODE_ENV=production
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_EDITOR_BASE_URL=${N8N_DOMAIN}
      - N8N_WEBHOOK_URL=${N8N_DOMAIN}
      - WEBHOOK_TUNNEL_URL=${N8N_DOMAIN}
      - N8N_ENDPOINT_REST=${N8N_DOMAIN}
      - N8N_PUBLIC_API_URL=${N8N_DOMAIN}/api/
      - N8N_WEBHOOK_TUNNEL_URL=${N8N_DOMAIN}/webhook/
      - N8N_WEBHOOK_BASE_URL=${N8N_DOMAIN}/webhook/
    expose:
      - "5678"
    restart: unless-stopped

  n8n-db:
    extends:
      file: compose.common.yaml
      service: n8n-db
    restart: unless-stopped

  adminer:
    extends:
      file: compose.common.yaml
      service: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
    expose:
      - "8080"
    restart: unless-stopped
