services:
  n8n:
    extends:
      file: compose.common.yaml
      service: n8n
    environment:
      - NODE_ENV=development
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_WEBHOOK_URL=http://localhost:5678
      - N8N_SECURE_COOKIE=false
      - NODE_FUNCTION_ALLOW_EXTERNAL=ioredis
    ports:
      - "5678:5678"

  n8n-db:
    extends:
      file: compose.common.yaml
      service: n8n-db

  adminer:
    extends:
      file: compose.common.yaml
      service: adminer
    ports:
      - "8080:8080"

  portainer:
    extends:
      file: compose.common.yaml
      service: portainer
    ports:
      - "9000:9000"
    security_opt: []

  redis:
    extends:
      file: compose.common.yaml
      service: redis
    ports:
      - "6379:6379"

  n8n-worker:
    extends:
      file: compose.common.yaml
      service: n8n-worker
    environment:
      - NODE_ENV=development
      - NODE_FUNCTION_ALLOW_EXTERNAL=ioredis
