services:
  traefik:
    extends:
      file: compose.common.yaml
      service: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --log.level=INFO
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"

  n8n:
    extends:
      file: compose.common.yaml
      service: n8n
    environment:
      - NODE_ENV=production
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_EDITOR_BASE_URL=http://${N8N_DOMAIN}
      - N8N_WEBHOOK_URL=http://${N8N_DOMAIN}
      - WEBHOOK_TUNNEL_URL=http://${N8N_DOMAIN}
      - N8N_ENDPOINT_REST=http://${N8N_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_DOMAIN}`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.scheme=http"

  n8n-db:
    extends:
      file: compose.common.yaml
      service: n8n-db

  adminer:
    extends:
      file: compose.common.yaml
      service: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_DOMAIN}`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=web"
